# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e64b9d09bd97d81f32294367e58385ece532b978ba64e364e943c67fe63a33e35e8f8af65c0f5dd4482e3a410617ee7607d5cbb744d073c5a526fb8944d8440

test:
  secret_key_base: aa7cb10b3f9b56ffd9dc63c71843c16e1a2f74fc6ed1b7179fc9fa18e9cf2202d703be6f3cac2d74f88d3490939c8becb62edc6e4e635a5069531542d313326b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
